apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: cG9zdGdyZXM=        # base64 encoded value of "postgres"
  password: cGFzc3dvcmQ=        # base64 encoded value of "password"
