apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      initContainers:
        - name: django-migrate
          image: srishtisingh1/simple-extraction-demo:latest
          command: ["python", "manage.py", "migrate"]
          volumeMounts:
            - name: media-storage
              mountPath: /app/media
        - name: django-collectstatic
          image: srishtisingh1/simple-extraction-demo:latest
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          volumeMounts:
            - name: media-storage
              mountPath: /app/media

      containers:
        - name: django
          image: srishtisingh1/simple-extraction-demo:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: django-secret
          volumeMounts:
            - name: media-storage
              mountPath: /app/media

      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc
