apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      initContainers:
        - name: django-migrate
          image: srishtisingh1/simple-extraction-demo:latest
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - secretRef:
                name: django-secret
          volumeMounts:
            - name: static-files
              mountPath: /app/staticfiles

      containers:
        - name: django
          image: srishtisingh1/simple-extraction-demo:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: django-secret
          volumeMounts:
            - name: static-files
              mountPath: /app/staticfiles
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: django-static-pvc
